In [50]:
from sklearn.datasets import load_wine
import pandas as pd

In [51]:
# 1. 加载原始数据对象
wine = load_wine()

# 2. 将数值矩阵 (X) 转为 DataFrame，并贴上对应的特征标签
df = pd.DataFrame(wine.data, columns=wine.feature_names)

# 3. 将分类结果 (y) 作为一个新列加入表格
df['target'] = wine.target

In [52]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model performs better. Use the trained model to perform some predictions on test data.

In [53]:
df.groupby('target').size()

target
0    59
1    71
2    48
dtype: int64

In [54]:
df1 = df[['alcohol', 'malic_acid', 'color_intensity', 'od280/od315_of_diluted_wines','target']]
df1.head()

   alcohol  malic_acid  color_intensity  od280/od315_of_diluted_wines  target
0    14.23        1.71             5.64                          3.92       0
1    13.20        1.78             4.38                          3.40       0
2    13.16        2.36             5.68                          3.17       0
3    14.37        1.95             7.80                          3.45       0
4    13.24        2.59             4.32                          2.93       0

In [55]:
inputs = df1.drop('target', axis=1)
target = df1['target']
inputs.head(3)

   alcohol  malic_acid  color_intensity  od280/od315_of_diluted_wines
0    14.23        1.71             5.64                          3.92
1    13.20        1.78             4.38                          3.40
2    13.16        2.36             5.68                          3.17

In [56]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3)

In [63]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [64]:
model.fit(X_train, y_train)

GaussianNB()

In [66]:
model.score(X_test, y_test)

0.9122807017543859

In [ ]:
X_test[:10]

In [ ]:
y_test[:10]

In [ ]:
model.predict(X_test[:10])

In [ ]:
model.predict_proba(X_test[:10])

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
model2.fit(X_train, y_train)

In [ ]:
model2.score(X_test, y_test)

In [ ]:
model2.predict(X_test[:10])

In [ ]:
model2.predict_proba(X_test[:10])

In [ ]:
df[['color_intensity', 'hue']].corr()

In [ ]:
df.corr()

In [ ]:
df[['total_phenols', 'od280/od315_of_diluted_wines']].corr()

In [68]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.92      , 0.91666667, 0.95833333, 1.        , 0.91666667])